management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus
#management.endpoints.web.exposure.include=env, info, health
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always

